# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup=xyz.shelltime.jetbrains
pluginName=ShellTime
pluginRepositoryUrl=https://github.com/shelltime/coding-extension-jetbrains
pluginVersion=0.0.1

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild=241
pluginUntilBuild=253.*

# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#intellij-platform-extension
platformType=IC
platformVersion=2024.1

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
platformBundledPlugins=Git4Idea

# Gradle Configuration
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.parallel=true

# Kotlin Configuration
kotlin.stdlib.default.dependency=false
kotlin.code.style=official
